#!/usr/bin/env python3

# Python Host for EZDAQ
# Kevin Cuzner
#
# Requires PyUSB

import usb.core, usb.util
import argparse, time, struct

idVendor = 0x16c0
idProduct = 0x05dc
sManufacturer = 'kevincuzner.com'
sProduct = 'EZDAQ'


def find_device():
    for dev in usb.core.find(find_all=True, idVendor=idVendor, idProduct=idProduct):
        if usb.util.get_string(dev, dev.iManufacturer) == sManufacturer and \
                usb.util.get_string(dev, dev.iProduct) == sProduct:
            return dev

def main():
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

    dev = find_device()
    if dev is None:
        raise ValueError('No EZDAQ Found')
    dev.set_configuration()
    while True:
        rt = usb.util.build_request_type(usb.util.CTRL_IN, usb.util.CTRL_TYPE_VENDOR, usb.util.CTRL_RECIPIENT_DEVICE)
        raw_data = dev.ctrl_transfer(rt, 0x01, wIndex=0, data_or_wLength=256)
        data = struct.unpack('HHHHHHHHHH', raw_data)
        print(data)
        time.sleep(0.5)

if __name__ == '__main__':
    main()
